import StyleDictionary from 'style-dictionary';
import {
  resolveOverlay,
  resolveThemedValue,
  shadowToCss,
  tokenPathToCssVar,
} from './scripts/color-resolver.mjs';

const isPrimitive = (token) => token.filePath?.includes('/primitives/');
const isSemantic = (token) => token.filePath?.includes('/semantic/');
const isPrimitiveDimension = (token) =>
  isPrimitive(token) && (token.$type === 'dimension' || token.$type === 'number');
const isPrimitiveShadow = (token) => isPrimitive(token) && token.$type === 'shadow';
const isSemanticColor = (token) => isSemantic(token) && token.$type === 'color';

StyleDictionary.registerFormat({
  name: 'css/primitives',
  format({ dictionary }) {
    const vars = dictionary.allTokens.map((token) => {
      const name = tokenPathToCssVar(token.path);
      return `  ${name}: ${token.$value};`;
    });

    return [
      '/** Primitive spacing & radius — generated by Style Dictionary */',
      ':root {',
      ...vars,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/shadows',
  format({ dictionary }) {
    const vars = dictionary.allTokens.map((token) => {
      const name = tokenPathToCssVar(token.path);
      const value = shadowToCss(token.original.$value, 'light');
      return `  ${name}: ${value};`;
    });

    return [
      '/** Primitive shadows — generated by Style Dictionary */',
      ':root {',
      ...vars,
      '}',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'css/semantic-theme',
  format({ dictionary, options }) {
    const theme = options.theme ?? 'light';
    const vars = [];

    for (const token of dictionary.allTokens) {
      let value;

      if (
        token.path.join('.') === 'color.background.overlay' &&
        !token.original?.$value?.[theme]
      ) {
        value = resolveOverlay(token, theme);
      } else {
        value = resolveThemedValue(token.original?.$value, theme, token);
      }

      if (value === undefined) continue;

      const name = tokenPathToCssVar(token.path);
      vars.push(`  ${name}: ${value};`);
    }

    const selector =
      theme === 'light'
        ? ':root,\n[data-theme="light"]'
        : '[data-theme="dark"]';

    return [
      `/** Semantic color tokens — ${theme} theme (resolved at build time) */`,
      `${selector} {`,
      ...vars,
      '}',
      '',
    ].join('\n');
  },
});

/** @type {import('style-dictionary').Config} */
export default {
  source: ['tokens/primitives/**/*.json', 'tokens/semantic/**/*.json'],
  log: {
    warnings: 'warn',
    verbosity: 'default',
  },
  platforms: {
    primitives: {
      transformGroup: 'css',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'primitives.css',
          format: 'css/primitives',
          filter: isPrimitiveDimension,
        },
      ],
    },
    shadows: {
      transformGroup: 'css',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'shadows.css',
          format: 'css/shadows',
          filter: isPrimitiveShadow,
        },
      ],
    },
    'semantic-light': {
      transformGroup: 'css',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'semantic-light.css',
          format: 'css/semantic-theme',
          filter: isSemanticColor,
          options: { theme: 'light' },
        },
      ],
    },
    'semantic-dark': {
      transformGroup: 'css',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'semantic-dark.css',
          format: 'css/semantic-theme',
          filter: isSemanticColor,
          options: { theme: 'dark' },
        },
      ],
    },
    json: {
      transformGroup: 'js',
      buildPath: 'src/styles/generated/',
      files: [
        {
          destination: 'tokens.json',
          format: 'json/nested',
          filter: (token) => isPrimitiveDimension(token) || isSemanticColor(token),
        },
      ],
    },
  },
};
