/**
 * Design system icons — Phosphor Icons (React).
 * Import from here (not `@phosphor-icons/react` directly) for a stable, curated set.
 *
 * Export names keep the previous Lucide-oriented API so call sites stay stable.
 * Default weight is Phosphor’s `regular`. Prefer `weight="bold"` or `fill` for
 * emphasis; use `duotone` sparingly for marketing / empty states.
 */
export {
  AlignRight as AlignEndVertical,
  Archive,
  ArrowRight,
  ArrowUp,
  Bell,
  CalendarDots as CalendarDays,
  Check,
  Checks as CheckCheck,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretUpDown as ChevronsUpDown,
  WarningCircle as CircleAlert,
  CheckCircle as CircleCheck,
  MinusCircle as CircleMinus,
  Question as CircleQuestionMark,
  Clock,
  Copy,
  DotsThreeVertical as EllipsisVertical,
  Info,
  Lightbulb,
  Database,
  FileText,
  Folder,
  Kanban as FolderKanban,
  SquaresFour as LayoutGrid,
  ListChecks as ListTodo,
  CircleNotch as LoaderCircle,
  ArrowsOut as Maximize2,
  ChatCircleDots as MessageCircleMore,
  Chat as MessageSquare,
  Microphone as Mic,
  Minus,
  Sidebar as PanelLeft,
  SidebarSimple as PanelRightClose,
  PencilSimpleLine as PencilLine,
  Plus,
  ArrowsClockwise as RefreshCw,
  ArrowClockwise as RotateCw,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Sparkle as Sparkles,
  ListDashes as TableOfContents,
  ThumbsDown,
  ThumbsUp,
  Trash as Trash2,
  Triangle,
  Warning as TriangleAlert,
  UploadSimple as Upload,
  User,
  X,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
} from '@phosphor-icons/react';
