/**
 * Design system icons — Lucide React.
 * Import from here (not `lucide-react` directly) for a stable, curated set.
 *
 * Stroke weight uses Lucide’s default (relative to size / viewBox). That matches
 * mature icon sets (Material opsz, SF Symbols optical weight, Lucide/Tabler
 * defaults): small icons stay light; large icons don’t go hairline.
 * Prefer `absoluteStrokeWidth` only for intentionally large display icons.
 */
export {
  AlignEndVertical,
  Archive,
  ArrowRight,
  ArrowUp,
  Bell,
  CalendarDays,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CircleMinus,
  Clock,
  EllipsisVertical,
  Info,
  Lightbulb,
  Database,
  FileText,
  Folder,
  FolderKanban,
  LayoutGrid,
  ListTodo,
  LoaderCircle,
  Maximize2,
  MessageCircleMore,
  MessageSquare,
  Mic,
  Minus,
  PanelLeft,
  PanelRightClose,
  PencilLine,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  Triangle,
  TriangleAlert,
  Upload,
  User,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
